travis:
  secure:
    BINSTAR_TOKEN: LM7sjholaOeI+5/Q+WCTqkHX2URf3TvFrzv8jy4grGX1JByPGe6hM8zU9uc/JEPX0K11sAZRk7BGVBtk+SWxUPsXPXMSg2RJKbHqxRZjbOmUQx65VG2lgUIzWgqXCgzlVzYl548ZnZOLCR5UaqsGeVKVqnFCT4FbIG/GeYFGSmCtNhpPiZCPVXqrEdF5BSre+0ET/gYoeb01FA9LUd4kN4eT3a6ZhaLmIsdUpuCFAqyNe+JS7AdmtCekcyl6lNFVaj9GjK+w9qE45yT5eJ5r/N+0YEkqWDOcF/zmk6wVh9OoDthcEo0k9qStLHTNPWywqMLkupSBBPVrHqZldbAeG9oh26/UZOOvKWpCKFhHPRt1cixQ/Ojkg81REtHkQgLLmnzxRu/EmpbUc9z3fgBzO/Z1AkalOxDlLRop1eDjWG8Wr1apBO0CKwtACQe6OgaVVTNxqv8AMK76hYwnsSPDfgEEYc0uQeIj2ZwubyD1k4C79V/Wch2K01vSAxUn7iY7bNBkcOQiZ7n8LzqhObgG6tCZtjK/A4kMbF0Y/v6+OyUX0SHl65knMr8KlShxJ7uY6c9KSirKm2cPumRQmkVWJwDIZ2fHWlR6rTkZeszvBrA41XQQCjx5LARfsg7+Z9EmdjSkPAXitKFHnRXWux0qi7caYP+o7GrH7+EO4Ke6fAQ=
provider: {win: azure}
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
